# Build the original id Software LinuxDOOM 1.10 source directly for browsers.
# Platform-specific i_*.c files are replaced by files from direct-port/ before make.

CC := emcc

PORT_FLAGS := -sUSE_SDL=2 -sUSE_SDL_MIXER=2

CFLAGS := -O2 -std=gnu89 -DNORMALUNIX -D__EMSCRIPTEN__ $(PORT_FLAGS) \
  -Wno-implicit-int \
  -Wno-implicit-function-declaration \
  -Wno-int-conversion \
  -Wno-incompatible-pointer-types \
  -Wno-deprecated-non-prototype \
  -Wno-parentheses \
  -Wno-unused-value \
  -Wno-format

SOURCES := \
  doomdef.c doomstat.c dstrings.c \
  i_system.c i_sound.c i_music_opl_bridge.c i_video.c i_net.c \
  tables.c f_finale.c f_wipe.c d_main.c d_net.c d_items.c g_game.c \
  m_menu.c m_misc.c m_argv.c m_bbox.c m_fixed.c m_swap.c m_cheat.c m_random.c \
  am_map.c p_ceilng.c p_doors.c p_enemy.c p_floor.c p_inter.c p_lights.c \
  p_map.c p_maputl.c p_plats.c p_pspr.c p_setup.c p_sight.c p_spec.c \
  p_switch.c p_mobj.c p_telept.c p_tick.c p_saveg.c p_user.c \
  r_bsp.c r_data.c r_draw.c r_main.c r_plane.c r_segs.c r_sky.c r_things.c \
  w_wad.c wi_stuff.c v_video.c st_lib.c st_stuff.c hu_stuff.c hu_lib.c \
  s_sound.c z_zone.c info.c sounds.c i_main.c

EMFLAGS := $(PORT_FLAGS) \
  -sASYNCIFY=1 \
  -sALLOW_MEMORY_GROWTH=1 \
  -sINITIAL_MEMORY=67108864 \
  -sSTACK_SIZE=1048576 \
  -sFORCE_FILESYSTEM=1 \
  -sASSERTIONS=1 \
  -sENVIRONMENT=web \
  -sINVOKE_RUN=0 \
  -sEXIT_RUNTIME=0 \
  -sEXPORTED_RUNTIME_METHODS=callMain,FS \
  --preload-file doom1.wad@doom1.wad \
  --shell-file shell.html

all: webdoom.html

webdoom.html: $(SOURCES) doom1.wad shell.html
	$(CC) $(CFLAGS) $(SOURCES) -o $@ $(EMFLAGS) -lm

clean:
	rm -f webdoom.html webdoom.js webdoom.wasm webdoom.data
